# nginx proxy address - http://172.17.0.1:59049

name: nginx-fpm
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: nginx-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      ERRORS: 0
      GIT_USE_SSH: 1
      REMOVE_FILES: 0
      REAL_IP_HEADER: 1
      DOMAIN: ${BASE_HOST_NAME:-$HOSTNAME}
      PHP_ERRORS_STDERR: 1
      HIDE_NGINX_HEADERS: 1
      PHP_POST_MAX_SIZE: 256m
      APPLICATION_ENV: production
      PHP_UPLOAD_MAX_FILESIZE: 1024m
    ports:
      - 172.17.0.1:59049:80
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/var/www/nginx/domains/${BASE_HOST_NAME:-$HOSTNAME}:/var/www/html'
    networks:
      - nginx
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://nginx-app:80'
      - 'cloudflare.hostname=nginx.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.nginx-app.entrypoints=http'
      - 'traefik.http.routers.nginx-app-secure.tls=true'
      - 'traefik.http.routers.nginx-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.nginx-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.nginx-app.middlewares=nginx-app-https-redirect'
      - 'traefik.http.routers.nginx-app-secure.entrypoints=https'
      - 'traefik.http.routers.nginx-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.nginx-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.nginx-app-secure.service=nginx-app'
      - 'traefik.http.services.nginx-app.loadbalancer.server.port=80'

networks:
  nginx:
    name: nginx
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
